# Generated by Django 3.1.4 on 2021-01-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20201206_2224'),
       # ('App1', '0002_auto_20210122_2054'),
    ]

    operations = [
    ]
